Creator: Dhanajit Brahma

Adapted from the original implementation in tensorflow from here: https://github.com/jsyoon0823/GAIN

Generative Adversarial Imputation Networks (GAIN) Implementation on Letter and Spam Dataset

Reference: J. Yoon, J. Jordon, M. van der Schaar, "GAIN: Missing Data Imputation using Generative Adversarial Nets," ICML, 2018.

In [1]:
#%% Packages
import torch
import numpy as np
from tqdm import tqdm
import torch.nn.functional as F

In [2]:
dataset_file = '/Users/gabrielketron/tpot2_addimputers/tpot2/ImputerExperiments/data/Spam.csv'  # 'Letter.csv' for Letter dataset an 'Spam.csv' for Spam dataset
use_gpu = False  # set it to True to use GPU and False to use CPU
if use_gpu:
    torch.cuda.set_device(0)

In [3]:
#%% System Parameters
# 1. Mini batch size
mb_size = 128
# 2. Missing rate
p_miss = 0.2
# 3. Hint rate
p_hint = 0.9
# 4. Loss Hyperparameters
alpha = 10
# 5. Train Rate
train_rate = 0.8

#%% Data

# Data generation
Data = np.loadtxt(dataset_file, delimiter=",",skiprows=1)

# Parameters
No = len(Data)
Dim = len(Data[0,:])

# Hidden state dimensions
H_Dim1 = Dim
H_Dim2 = Dim

# Normalization (0 to 1)
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)    

#%% Missing introducing
p_miss_vec = p_miss * np.ones((Dim,1)) 
   
Missing = np.zeros((No,Dim))

for i in range(Dim):
    A = np.random.uniform(0., 1., size = [len(Data),])
    B = A > p_miss_vec[i]
    Missing[:,i] = 1.*B

    
#%% Train Test Division    
   
idx = np.random.permutation(No)

Train_No = int(No * train_rate)
Test_No = No - Train_No
    
# Train / Test Features
trainX = Data[idx[:Train_No],:]
testX = Data[idx[Train_No:],:]

# Train / Test Missing Indicators
trainM = Missing[idx[:Train_No],:]
testM = Missing[idx[Train_No:],:]

#%% Necessary Functions

# 1. Xavier Initialization Definition
# def xavier_init(size):
#     in_dim = size[0]
#     xavier_stddev = 1. / tf.sqrt(in_dim / 2.)
#     return tf.random_normal(shape = size, stddev = xavier_stddev)
def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)
    
# Hint Vector Generation
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C
   

### GAIN Architecture   
GAIN Consists of 3 Components
- Generator
- Discriminator
- Hint Mechanism

In [4]:
#%% 1. Discriminator
if use_gpu is True:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       # Output is multi-variate
else:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # Output is multi-variate

theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

#%% 2. Generator
if use_gpu is True:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
else:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]

## GAIN Functions

In [5]:
#%% 1. Generator
def generator(new_x,m):
    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # Mask + Data Concatenate
    G_h1 = F.relu(torch.matmul(inputs, G_W1) + G_b1)
    G_h2 = F.relu(torch.matmul(G_h1, G_W2) + G_b2)   
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    
    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):
    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # Hint + Data Concatenate
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)  
    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] Probability Output
    
    return D_prob

#%% 3. Other functions
# Random sample generator for Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])        

# Mini-batch generation
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx

## GAIN Losses

In [6]:
def discriminator_loss(M, New_X, H):
    # Generator
    G_sample = generator(New_X,M)
    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8))
    return D_loss

def generator_loss(X, M, New_X, H):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8))
    MSE_train_loss = torch.mean((M * New_X - M * G_sample)**2) / torch.mean(M)

    G_loss = G_loss1 + alpha * MSE_train_loss 

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return G_loss, MSE_train_loss, MSE_test_loss
    
def test_loss(X, M, New_X):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return MSE_test_loss, G_sample

## Optimizers

In [7]:
optimizer_D = torch.optim.Adam(params=theta_D)
optimizer_G = torch.optim.Adam(params=theta_G)

## Training

In [8]:
#%% Start Iterations
for it in tqdm(range(5000)):    
    
    #%% Inputs
    mb_idx = sample_idx(Train_No, mb_size)
    X_mb = trainX[mb_idx,:]  
    
    Z_mb = sample_Z(mb_size, Dim) 
    M_mb = trainM[mb_idx,:]  
    H_mb1 = sample_M(mb_size, Dim, 1-p_hint)
    H_mb = M_mb * H_mb1
    
    New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce
    
    if use_gpu is True:
        X_mb = torch.tensor(X_mb, device="cuda")
        M_mb = torch.tensor(M_mb, device="cuda")
        H_mb = torch.tensor(H_mb, device="cuda")
        New_X_mb = torch.tensor(New_X_mb, device="cuda")
    else:
        X_mb = torch.tensor(X_mb)
        M_mb = torch.tensor(M_mb)
        H_mb = torch.tensor(H_mb)
        New_X_mb = torch.tensor(New_X_mb)
    
    optimizer_D.zero_grad()
    D_loss_curr = discriminator_loss(M=M_mb, New_X=New_X_mb, H=H_mb)
    D_loss_curr.backward()
    optimizer_D.step()
    
    optimizer_G.zero_grad()
    G_loss_curr, MSE_train_loss_curr, MSE_test_loss_curr = generator_loss(X=X_mb, M=M_mb, New_X=New_X_mb, H=H_mb)
    G_loss_curr.backward()
    optimizer_G.step()    
        
    #%% Intermediate Losses
    if it % 100 == 0:
        print('Iter: {}'.format(it))
        print('Train_loss: {:.4}'.format(np.sqrt(MSE_train_loss_curr.item())))
        print('Test_loss: {:.4}'.format(np.sqrt(MSE_test_loss_curr.item())))
        print()

  1%|▏         | 70/5000 [00:00<00:13, 369.65it/s]

Iter: 0
Train_loss: 0.4889
Test_loss: 0.4922



  3%|▎         | 150/5000 [00:00<00:12, 386.40it/s]

Iter: 100
Train_loss: 0.05647
Test_loss: 0.06879



  6%|▌         | 276/5000 [00:00<00:11, 404.36it/s]

Iter: 200
Train_loss: 0.05768
Test_loss: 0.06676



  7%|▋         | 363/5000 [00:00<00:11, 419.73it/s]

Iter: 300
Train_loss: 0.05731
Test_loss: 0.04991



  9%|▉         | 448/5000 [00:01<00:10, 414.01it/s]

Iter: 400
Train_loss: 0.0562
Test_loss: 0.08091



 12%|█▏        | 581/5000 [00:01<00:10, 435.35it/s]

Iter: 500
Train_loss: 0.05106
Test_loss: 0.05805



 13%|█▎        | 672/5000 [00:01<00:10, 429.90it/s]

Iter: 600
Train_loss: 0.05557
Test_loss: 0.07003



 15%|█▌        | 760/5000 [00:01<00:09, 425.46it/s]

Iter: 700
Train_loss: 0.05275
Test_loss: 0.05305



 17%|█▋        | 857/5000 [00:02<00:09, 452.02it/s]

Iter: 800
Train_loss: 0.05609
Test_loss: 0.06651



 19%|█▉        | 944/5000 [00:02<00:10, 385.49it/s]

Iter: 900
Train_loss: 0.04847
Test_loss: 0.05844



 21%|██▏       | 1072/5000 [00:02<00:09, 413.29it/s]

Iter: 1000
Train_loss: 0.05081
Test_loss: 0.06479



 23%|██▎       | 1164/5000 [00:02<00:08, 429.07it/s]

Iter: 1100
Train_loss: 0.04222
Test_loss: 0.05297



 25%|██▌       | 1253/5000 [00:03<00:09, 416.22it/s]

Iter: 1200
Train_loss: 0.04347
Test_loss: 0.06565



 28%|██▊       | 1380/5000 [00:03<00:08, 407.55it/s]

Iter: 1300
Train_loss: 0.04154
Test_loss: 0.0502



 29%|██▉       | 1472/5000 [00:03<00:08, 431.66it/s]

Iter: 1400
Train_loss: 0.04806
Test_loss: 0.06462



 31%|███▏      | 1564/5000 [00:03<00:08, 428.51it/s]

Iter: 1500
Train_loss: 0.04883
Test_loss: 0.07136



 33%|███▎      | 1647/5000 [00:04<00:08, 381.66it/s]

Iter: 1600
Train_loss: 0.04425
Test_loss: 0.05154



 36%|███▌      | 1778/5000 [00:04<00:07, 417.08it/s]

Iter: 1700
Train_loss: 0.04294
Test_loss: 0.0469



 37%|███▋      | 1873/5000 [00:04<00:07, 421.61it/s]

Iter: 1800
Train_loss: 0.03751
Test_loss: 0.05523



 38%|███▊      | 1916/5000 [00:04<00:07, 422.44it/s]

Iter: 1900
Train_loss: 0.03737
Test_loss: 0.06511



 41%|████      | 2031/5000 [00:05<00:09, 312.73it/s]

Iter: 2000
Train_loss: 0.03311
Test_loss: 0.06344



 43%|████▎     | 2166/5000 [00:05<00:07, 394.03it/s]

Iter: 2100
Train_loss: 0.0341
Test_loss: 0.04918



 45%|████▌     | 2258/5000 [00:05<00:06, 420.68it/s]

Iter: 2200
Train_loss: 0.03499
Test_loss: 0.06729



 47%|████▋     | 2342/5000 [00:05<00:06, 395.87it/s]

Iter: 2300
Train_loss: 0.03538
Test_loss: 0.05846



 49%|████▉     | 2474/5000 [00:06<00:06, 419.50it/s]

Iter: 2400
Train_loss: 0.03382
Test_loss: 0.06549



 51%|█████     | 2559/5000 [00:06<00:05, 415.23it/s]

Iter: 2500
Train_loss: 0.03406
Test_loss: 0.0587



 53%|█████▎    | 2652/5000 [00:06<00:05, 439.14it/s]

Iter: 2600
Train_loss: 0.03064
Test_loss: 0.04733



 55%|█████▍    | 2748/5000 [00:06<00:04, 456.35it/s]

Iter: 2700
Train_loss: 0.02982
Test_loss: 0.06488



 58%|█████▊    | 2894/5000 [00:07<00:04, 471.97it/s]

Iter: 2800
Train_loss: 0.02872
Test_loss: 0.04252



 60%|█████▉    | 2990/5000 [00:07<00:04, 469.15it/s]

Iter: 2900
Train_loss: 0.0313
Test_loss: 0.05852



 62%|██████▏   | 3084/5000 [00:07<00:04, 453.22it/s]

Iter: 3000
Train_loss: 0.02809
Test_loss: 0.04728



 64%|██████▎   | 3179/5000 [00:07<00:03, 461.41it/s]

Iter: 3100
Train_loss: 0.031
Test_loss: 0.0545



 65%|██████▌   | 3270/5000 [00:07<00:04, 418.47it/s]

Iter: 3200
Train_loss: 0.03014
Test_loss: 0.0632



 67%|██████▋   | 3363/5000 [00:08<00:03, 437.81it/s]

Iter: 3300
Train_loss: 0.02492
Test_loss: 0.0537



 69%|██████▉   | 3457/5000 [00:08<00:03, 451.49it/s]

Iter: 3400
Train_loss: 0.02606
Test_loss: 0.04827



 71%|███████   | 3553/5000 [00:08<00:03, 462.48it/s]

Iter: 3500
Train_loss: 0.02377
Test_loss: 0.06637



 73%|███████▎  | 3651/5000 [00:08<00:03, 432.94it/s]

Iter: 3600
Train_loss: 0.02573
Test_loss: 0.05859



 76%|███████▌  | 3792/5000 [00:09<00:02, 448.15it/s]

Iter: 3700
Train_loss: 0.03071
Test_loss: 0.06318



 77%|███████▋  | 3839/5000 [00:09<00:02, 452.91it/s]

Iter: 3800
Train_loss: 0.02382
Test_loss: 0.04404



 80%|███████▉  | 3978/5000 [00:09<00:02, 444.16it/s]

Iter: 3900
Train_loss: 0.02294
Test_loss: 0.05952



 81%|████████▏ | 4072/5000 [00:09<00:02, 455.59it/s]

Iter: 4000
Train_loss: 0.02425
Test_loss: 0.07006



 83%|████████▎ | 4164/5000 [00:09<00:01, 449.32it/s]

Iter: 4100
Train_loss: 0.0231
Test_loss: 0.08163



 85%|████████▌ | 4258/5000 [00:10<00:01, 457.82it/s]

Iter: 4200
Train_loss: 0.02564
Test_loss: 0.06228



 87%|████████▋ | 4354/5000 [00:10<00:01, 448.27it/s]

Iter: 4300
Train_loss: 0.02144
Test_loss: 0.04986



 89%|████████▉ | 4448/5000 [00:10<00:01, 453.97it/s]

Iter: 4400
Train_loss: 0.0268
Test_loss: 0.06335



 91%|█████████ | 4543/5000 [00:10<00:01, 418.99it/s]

Iter: 4500
Train_loss: 0.02125
Test_loss: 0.04587



 94%|█████████▎| 4686/5000 [00:11<00:00, 457.22it/s]

Iter: 4600
Train_loss: 0.02333
Test_loss: 0.03814



 96%|█████████▌| 4782/5000 [00:11<00:00, 466.82it/s]

Iter: 4700
Train_loss: 0.02654
Test_loss: 0.0632



 98%|█████████▊| 4877/5000 [00:11<00:00, 469.41it/s]

Iter: 4800
Train_loss: 0.0202
Test_loss: 0.04113



 99%|█████████▉| 4973/5000 [00:11<00:00, 468.15it/s]

Iter: 4900
Train_loss: 0.02093
Test_loss: 0.05443



100%|██████████| 5000/5000 [00:11<00:00, 425.80it/s]


## Testing

In [9]:
Z_mb = sample_Z(Test_No, Dim) 
M_mb = testM
X_mb = testX
        
New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

if use_gpu is True:
    X_mb = torch.tensor(X_mb, device='cuda')
    M_mb = torch.tensor(M_mb, device='cuda')
    New_X_mb = torch.tensor(New_X_mb, device='cuda')
else:
    X_mb = torch.tensor(X_mb)
    M_mb = torch.tensor(M_mb)
    New_X_mb = torch.tensor(New_X_mb)
    
MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)
        
print('Final Test RMSE: ' + str(np.sqrt(MSE_final.item())))

Final Test RMSE: 0.04954538781548618


In [10]:
imputed_data = M_mb * X_mb + (1-M_mb) * Sample
print("Imputed test data:")
# np.set_printoptions(formatter={'float': lambda x: "{0:0.8f}".format(x)})

if use_gpu is True:
    print(imputed_data.cpu().detach().numpy())
else:
    print(imputed_data.detach().numpy())

Imputed test data:
[[0.01038265 0.         0.13529409 ... 0.0002433  0.00030036 0.02785766]
 [0.         0.00220431 0.04269501 ... 0.00231956 0.00170204 0.01189184]
 [0.         0.01540616 0.         ... 0.00359873 0.01511814 0.04444444]
 ...
 [0.         0.         0.01198764 ... 0.         0.         0.00037879]
 [0.         0.00433719 0.         ... 0.006601   0.00680817 0.01015121]
 [0.03524228 0.         0.12450982 ... 0.00022696 0.00110132 0.00386527]]
